# Generated by Django 4.2.3 on 2023-09-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_globalsettings_playvideo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='playVideo',
            new_name='media_audio',
        ),
        migrations.RenameField(
            model_name='globalsettings',
            old_name='playWithAudio',
            new_name='media_display',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='media_sequence',
            field=models.IntegerField(default=4),
        ),
    ]
