# Generated by Django 4.2.3 on 2023-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_playvideo_globalsettings_media_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='water',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='first_storey_ablution',
            field=models.CharField(default='#808000', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='first_storey_toilet',
            field=models.CharField(default='#000080', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ground_storey_cold_ablution',
            field=models.CharField(default='#008000', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ground_storey_geyser',
            field=models.CharField(default='#800000', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ground_storey_hot_ablution',
            field=models.CharField(default='#00FFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ground_storey_toilet',
            field=models.CharField(default='#FF00FF', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='second_storey_ablution',
            field=models.CharField(default='#009099', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='second_storey_kitchen',
            field=models.CharField(default='#00FF00', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='second_storey_toilet',
            field=models.CharField(default='#0000FF', max_length=20),
        ),
    ]
