# Generated by Django 4.2.3 on 2023-09-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_globalsettings_water_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='second_storey_kitchen',
            new_name='secondary_storey_kitchen',
        ),
    ]
