# Generated by Django 4.2.3 on 2023-09-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_second_storey_kitchen_globalsettings_secondary_storey_kitchen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='incomerPower',
            new_name='incomer_power',
        ),
        migrations.RenameField(
            model_name='globalsettings',
            old_name='solarPower',
            new_name='solar_power',
        ),
    ]
