# Generated by Django 4.2.3 on 2023-09-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_uploadedvideo_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedvideo',
            old_name='video',
            new_name='video_file',
        ),
    ]
