name: Cypress and Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
        python-version: [3.11]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup Python and Django backend
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Django dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start Django server
      working-directory: ./backend
      run: python manage.py runserver 8000 &

    # Setup Node.js and Cypress frontend
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install
    - name: Cypress run
      working-directory: ./frontend
      uses: cypress-io/github-action@v6
      with:
        start: npm start
        wait-on: 'http://localhost:3000,http://localhost:8000'
        record: true
        parallel: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
